/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Pepito
 */
public class UserInterface extends javax.swing.JFrame {

    private final String user;
    private final int CAPITOLATOINDEX = 0, PROGETTOINDEX = 1, COMPUTOINDEX = 2;
    
    /**
     * Creates new form UserInterface
     * @param user
     */
    public UserInterface(String user) {
        this.user = user;
        initComponents();
        tabbedPane.setEnabledAt(COMPUTOINDEX, false);
    }
    
    public UserInterface() {
        this.user = "NON_ADMIN";
        initComponents();
        tabbedPane.setSelectedIndex(PROGETTOINDEX);
        tabbedPane.setEnabledAt(CAPITOLATOINDEX, false);
        tabbedPane.setEnabledAt(COMPUTOINDEX, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        capitolatoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addVoceButton = new javax.swing.JButton();
        deleteVoceButton = new javax.swing.JButton();
        modifyVoceButton = new javax.swing.JButton();
        progettoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        openProgettoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createProgettoButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        computoPanel = new javax.swing.JPanel();
        computoComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        createComputoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HouseHub");

        capitolatoPanel.setBackground(new java.awt.Color(240, 245, 58));
        capitolatoPanel.setLayout(new java.awt.GridLayout(4, 2));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Capitolato clienti");
        capitolatoPanel.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Capitolato sub-appaltatori");
        capitolatoPanel.add(jLabel6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codice", "Descrizione", "Unità di misura", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        capitolatoPanel.add(jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codice", "Descrizione", "Unità di misura", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        capitolatoPanel.add(jScrollPane2);

        addVoceButton.setText("Aggiungi nuova voce");
        addVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoceButtonActionPerformed(evt);
            }
        });
        capitolatoPanel.add(addVoceButton);

        deleteVoceButton.setText("Elimina voce");
        deleteVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVoceButtonActionPerformed(evt);
            }
        });
        capitolatoPanel.add(deleteVoceButton);

        modifyVoceButton.setText("Apporta modifiche");
        modifyVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyVoceButtonActionPerformed(evt);
            }
        });
        capitolatoPanel.add(modifyVoceButton);

        tabbedPane.addTab("Capitolato", capitolatoPanel);

        progettoPanel.setBackground(new java.awt.Color(240, 245, 58));
        progettoPanel.setLayout(new java.awt.GridLayout(2, 3, 50, 50));
        progettoPanel.add(jLabel1);

        openProgettoButton.setText("Apri progetto");
        openProgettoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProgettoButtonActionPerformed(evt);
            }
        });
        progettoPanel.add(openProgettoButton);
        progettoPanel.add(jLabel2);
        progettoPanel.add(jLabel4);

        createProgettoButton.setText("Crea progetto");
        createProgettoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProgettoButtonActionPerformed(evt);
            }
        });
        progettoPanel.add(createProgettoButton);
        progettoPanel.add(jLabel8);

        tabbedPane.addTab("Progetto", progettoPanel);

        computoPanel.setBackground(new java.awt.Color(240, 245, 58));
        computoPanel.setLayout(new java.awt.GridLayout(2, 2, 50, 50));

        computoPanel.add(computoComboBox);

        jButton2.setText("Visualizza");
        computoPanel.add(jButton2);
        computoPanel.add(jLabel3);

        createComputoButton.setText("Crea nuovo computo");
        createComputoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createComputoButtonActionPerformed(evt);
            }
        });
        computoPanel.add(createComputoButton);

        tabbedPane.addTab("Computo", computoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProgettoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProgettoButtonActionPerformed
        //Apri finestra per inserire dati dell'utente
        
        //Recupera il controllo e visualizza il progetto corrente nella scheda Computo
    }//GEN-LAST:event_createProgettoButtonActionPerformed

    private void openProgettoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProgettoButtonActionPerformed
        //Scegli cartella da aprire

        //visualizza il progetto corrente nella scheda Computo
    }//GEN-LAST:event_openProgettoButtonActionPerformed

    private void createComputoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createComputoButtonActionPerformed
        //Seleziona le voci disponibili del capitolato in un'altra finestra
        
        //Recupera il controllo e visualizza il computo corrente
    }//GEN-LAST:event_createComputoButtonActionPerformed

    private void addVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoceButtonActionPerformed
        //Nuova interfaccia per inserire la nuova voce
        
        //Recupera il controllo e visualizza le voci
    }//GEN-LAST:event_addVoceButtonActionPerformed

    private void deleteVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVoceButtonActionPerformed
        //Bisogna prima aver selezionato la voce
    }//GEN-LAST:event_deleteVoceButtonActionPerformed

    private void modifyVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyVoceButtonActionPerformed
        // Salva su file con path e nome predefiniti
    }//GEN-LAST:event_modifyVoceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVoceButton;
    private javax.swing.JPanel capitolatoPanel;
    private javax.swing.JComboBox<String> computoComboBox;
    private javax.swing.JPanel computoPanel;
    private javax.swing.JButton createComputoButton;
    private javax.swing.JButton createProgettoButton;
    private javax.swing.JButton deleteVoceButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton modifyVoceButton;
    private javax.swing.JButton openProgettoButton;
    private javax.swing.JPanel progettoPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
