/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.EventQueue;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import models.Computo;
import models.Progetto;
import models.VoceComputo;

/**
 *
 * @author Pepito
 */
public class VoceComputoInterface extends javax.swing.JFrame {

    private VoceComputo voce;
    private Computo computo;
    private String fileProgetto;
    
    private ListModel voceModel;
    private DefaultTableModel misurazioniModel;
    
    private boolean saved;
    
    /**
     * Creates new form VoceComputoInterface
     */
    public VoceComputoInterface(VoceComputo voce, Computo computo, String fileProgetto) {
        this.voce = voce;
        this.computo = computo;
        this.fileProgetto = fileProgetto;
        this.saved = true;
        initComponents();
        voceModel = voceList.getModel();
        misurazioniModel = (DefaultTableModel) misurazioniTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        misurazioniTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addVoceButton = new javax.swing.JButton();
        removeVoceButton = new javax.swing.JButton();
        addMisurazioneButton = new javax.swing.JButton();
        removeMisurazioneButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));
        jPanel2.setLayout(new java.awt.BorderLayout());

        misurazioniTable.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        misurazioniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Misurazione", "Parti uguali", "Lunghezza", "Larghezza", "Altezza/peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(misurazioniTable);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("                            Misurazioni");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(149, 165, 166));

        addVoceButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        addVoceButton.setText("Aggiungi voce");
        addVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoceButtonActionPerformed(evt);
            }
        });

        removeVoceButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        removeVoceButton.setText("Rimuovi voce");
        removeVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeVoceButtonActionPerformed(evt);
            }
        });

        addMisurazioneButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        addMisurazioneButton.setText("Aggiungi misurazione");
        addMisurazioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMisurazioneButtonActionPerformed(evt);
            }
        });

        removeMisurazioneButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        removeMisurazioneButton.setText("Elimina misurazione");
        removeMisurazioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMisurazioneButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        saveButton.setText("Salva");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMisurazioneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeVoceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addVoceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeMisurazioneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(addVoceButton)
                .addGap(43, 43, 43)
                .addComponent(removeVoceButton)
                .addGap(37, 37, 37)
                .addComponent(addMisurazioneButton)
                .addGap(43, 43, 43)
                .addComponent(removeMisurazioneButton)
                .addGap(42, 42, 42)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(149, 165, 166));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Vedi voce");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save() {
        try {
            Progetto p = Progetto.caricaProgetto(fileProgetto);
            p.rimuoviComputo(computo);
            computo.rimuoviVoce(voce);
            
            computo.aggiungiVoce(voce);
            p.aggiungiComputo(computo);
            p.salvaProgetto(fileProgetto);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(saved == false) {
            int choice = JOptionPane.showConfirmDialog(this, "Vuoi salvare prima di chiudere?");
            if(choice == JOptionPane.YES_OPTION)
                save();
            else if(choice == JOptionPane.CANCEL_OPTION) 
                return;
        }
        
        EventQueue.invokeLater(() -> {
            new ComputoInterface().setVisible(true);
            dispose();
        });
    }//GEN-LAST:event_formWindowClosing

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        save();
        saved = true;
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoceButtonActionPerformed
        String newVoce = JOptionPane.showInputDialog(this, "Inserisci un vedi voce", "Nuova voce", JOptionPane.QUESTION_MESSAGE);
        
        try{
            int newVoceNum = Integer.parseInt(newVoce);
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Inserire un numero intero", "Avviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //voceModel.
        
        saved = false;
    }//GEN-LAST:event_addVoceButtonActionPerformed

    private void removeVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVoceButtonActionPerformed
        saved = false;
    }//GEN-LAST:event_removeVoceButtonActionPerformed

    private void addMisurazioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMisurazioneButtonActionPerformed
        saved = false;
    }//GEN-LAST:event_addMisurazioneButtonActionPerformed

    private void removeMisurazioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMisurazioneButtonActionPerformed
        saved = false;
    }//GEN-LAST:event_removeMisurazioneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoceComputoInterface(null).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMisurazioneButton;
    private javax.swing.JButton addVoceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable misurazioniTable;
    private javax.swing.JButton removeMisurazioneButton;
    private javax.swing.JButton removeVoceButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
