/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.EventQueue;
import java.io.IOException;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Computo;
import models.Progetto;
import models.VoceComputo;

/**
 *
 * @author Pepito
 */
public class VoceComputoInterface extends javax.swing.JFrame {

    private VoceComputo voce;
    private Computo computo;
    private String fileProgetto;

    private DefaultTableModel voceModel, misurazioniModel;

    private boolean saved;

    /**
     * Creates new form VoceComputoInterface
     */
    public VoceComputoInterface(VoceComputo voce, Computo computo, String fileProgetto) {
        this.voce = voce;
        this.computo = computo;
        this.fileProgetto = fileProgetto;
        this.saved = true;
        initComponents();
        misurazioniLabel.setText("Misurazioni (" + voce.getUnitaDiMisura() + ")");
        voceModel = (DefaultTableModel) voceTable.getModel();
        misurazioniModel = (DefaultTableModel) misurazioniTable.getModel();
    }

    private void refreshTables() {
        voceModel.setRowCount(0);
        misurazioniModel.setRowCount(0);

        for (int numVediVoce : voce.getVediVoce().keySet()) {
            VoceComputo vediVoce = computo.getVociComputo().get(numVediVoce);
            Object[] rowData = {numVediVoce, vediVoce.getUnitaDiMisura(), vediVoce.getQuantita()};
            voceModel.addRow(rowData);
        }

        for (int i = 0; i < voce.getPartiUguali().size(); i++) {
            Object[] rowData = {voce.getMisurazioni().get(i),voce.getPartiUguali().get(i), 
                voce.getLunghezze().get(i),voce.getLarghezze().get(i), voce.getAltezze_pesi().get(i)};
            misurazioniModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        misurazioniTable = new javax.swing.JTable();
        misurazioniTable.setDefaultRenderer(String.class, new MultiLineTableCellRenderer());
        misurazioniLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addVoceButton = new javax.swing.JButton();
        removeVoceButton = new javax.swing.JButton();
        addMisurazioneButton = new javax.swing.JButton();
        removeMisurazioneButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        voceTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));
        jPanel2.setLayout(new java.awt.BorderLayout());

        misurazioniTable.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        misurazioniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Misurazione", "Parti uguali", "Lunghezza", "Larghezza", "Altezza/peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(misurazioniTable);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        misurazioniLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        misurazioniLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        misurazioniLabel.setText("Misurazioni");
        jPanel2.add(misurazioniLabel, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(149, 165, 166));

        addVoceButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        addVoceButton.setText("Aggiungi vedi voce");
        addVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoceButtonActionPerformed(evt);
            }
        });

        removeVoceButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        removeVoceButton.setText("Rimuovi vedi voce");
        removeVoceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeVoceButtonActionPerformed(evt);
            }
        });

        addMisurazioneButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        addMisurazioneButton.setText("Aggiungi misurazione");
        addMisurazioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMisurazioneButtonActionPerformed(evt);
            }
        });

        removeMisurazioneButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        removeMisurazioneButton.setText("Elimina misurazione");
        removeMisurazioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMisurazioneButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        saveButton.setText("Salva");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMisurazioneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeVoceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addVoceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeMisurazioneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(addVoceButton)
                .addGap(43, 43, 43)
                .addComponent(removeVoceButton)
                .addGap(37, 37, 37)
                .addComponent(addMisurazioneButton)
                .addGap(43, 43, 43)
                .addComponent(removeMisurazioneButton)
                .addGap(42, 42, 42)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(149, 165, 166));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Vedi voce");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        voceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Unità di misura", "Quantità"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(voceTable);
        if (voceTable.getColumnModel().getColumnCount() > 0) {
            voceTable.getColumnModel().getColumn(0).setMinWidth(50);
            voceTable.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save() {
        try {
            Progetto p = Progetto.caricaProgetto(fileProgetto);
            p.rimuoviComputo(computo);
            computo.rimuoviVoce(voce);

            computo.aggiungiVoce(voce);
            p.aggiungiComputo(computo);
            p.salvaProgetto(fileProgetto);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (saved == false) {
            int choice = JOptionPane.showConfirmDialog(this, "Vuoi salvare prima di chiudere?");
            if (choice == JOptionPane.YES_OPTION) {
                save();
            } else if (choice == JOptionPane.CANCEL_OPTION) {
                return;
            }
        }

        EventQueue.invokeLater(() -> {
            new ComputoInterface().setVisible(true);
            dispose();
        });
    }//GEN-LAST:event_formWindowClosing

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        save();
        saved = true;
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoceButtonActionPerformed
        String newVoce = JOptionPane.showInputDialog(this, "Inserisci un vedi voce", "Nuova voce", JOptionPane.QUESTION_MESSAGE);

        if (newVoce == null) {
            return;
        }

        try {
            int newVoceNum = Integer.parseInt(newVoce);
            
            TreeMap<Integer, VoceComputo> voci = computo.getVociComputo();
            
            if(!voci.containsKey(newVoceNum) || newVoceNum >= voce.getNumeroProgressivo()) {
                JOptionPane.showMessageDialog(this, "Inserire un numero di voce minore di quella corrente", "Avviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            voce.aggiungiVediVoce(voci.get(newVoceNum));
            refreshTables();
            saved = false;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Inserire un numero intero", "Avviso", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_addVoceButtonActionPerformed

    private void removeVoceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVoceButtonActionPerformed
        int selectedRow = voceTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleziona una voce", "Avviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        voce.rimuoviVediVoce((int) voceModel.getValueAt(selectedRow, 0));
        refreshTables();
        saved = false;
    }//GEN-LAST:event_removeVoceButtonActionPerformed

    private void addMisurazioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMisurazioneButtonActionPerformed
        String newMis = JOptionPane.showInputDialog(this, "Inserisci una misurazione", "Nuova misurazione", JOptionPane.QUESTION_MESSAGE);

        if (newMis == null || newMis.equals("")) {
            return;
        }

        voce.aggiungiDimensioni(newMis, 0, 0, 0, 0);
        refreshTables();
        saved = false;
    }//GEN-LAST:event_addMisurazioneButtonActionPerformed

    private void removeMisurazioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMisurazioneButtonActionPerformed
        int selectedRow = misurazioniTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleziona una misurazione", "Avviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        voce.rimuoviDimensioni(selectedRow);
        refreshTables();
        saved = false;
    }//GEN-LAST:event_removeMisurazioneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoceComputoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoceComputoInterface(null).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMisurazioneButton;
    private javax.swing.JButton addVoceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel misurazioniLabel;
    private javax.swing.JTable misurazioniTable;
    private javax.swing.JButton removeMisurazioneButton;
    private javax.swing.JButton removeVoceButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable voceTable;
    // End of variables declaration//GEN-END:variables
}
